### ISSUE TITLE
Does spline-based probability calibration keeps the relative ordering of the probabilities like Isotonic Regression?

### ISSUE THREAD

**Issue by robotenique** [numeristical/introspective#28]
As the question says, reading the notebook 'Probability Calibration using ML-Insights', even though Logloss is better using the spline calibration approach, I'd like to know if using this type of scaling can actually worsen the AUC of my model...

**Comment by blucena** [comment]
If the resulting calibration curve is monotonic, it will not change the AUC, since the relative ordering of test points is not changed.  In some cases, the resulting spline curve will not be monotonic.  This usually occurs with a poorly fit model.  For example, if a logistic regression is used to fit a non-monotonic effect.  In these cases, the ordering will change, and therefore the AUC will change as well.  It could make it worse, but if done right it should in fact improve the AUC.

**Comment by robotenique** [comment]
Thanks! I was just curious if there was some theoretical constraint of monotonicity.
