### ISSUE TITLE
Saving SplineCalibratedClassifierCV

### ISSUE THREAD

**Issue by AleksandrML** [numeristical/introspective#29]
Is it possible to save SplineCalibratedClassifierCV? 
I tried to do that with sklearn.joblib.dump but it does not work. 
I used calibration for keras model and it works surprisingly better in some range than an original model. Btw keras methods (like predict and predict_proba) work differently from base functionality of sklearn models, so I made a new class and redefined those methods to allow keras model being calibrated. However, I can not save it.

**Comment by blucena** [comment]
OK - yes, other people have asked for the ability to serialize these models, so we should find a solution.

One thing to note is that the `SplineCalibratedClassifierCV' object essentially does the following steps:
1) Get a set of (cross-validated) predictions `y_pred`
2) Call `prob_calibration_function` against the true answers and `y_pred` (possibly doing a `pre_transform` on `y_pred`).
3) Train the model on the full dataset
4) When predicting on new datapoints, it just applies the model from 3 (followed by the `pre_transform` if used) followed by the function outputted by `prob_calibration_function`.

So, one shortcut may be to serialize the function outputted by `prob_calibration_function` (if there is a way to make that work), and separately serialize the model trained on the full dataset and them apply them in succession.

**Comment by AleksandrML** [comment]
Well, if I already have an object SplineCalibratedClassifierCV which was already used as a calibrator for a base estimator (cv='prefit'), it looks like I can not do anything except trying to use mli.prob_calibration_function instead of already trained SplineCalibratedClassifierCV unfortunately. 
Then I have still 2 questions:
1) As far as I see the first call of mli.prob_calibration_function with train data makes some magic like 'train' and returns the function which I can use later as 'predict', right?
2) By choosing cv = 'prefit' during calibration I could choose the option to use train data without cv at all (it may be very important if one's data is time-series stuff - past always should be in train and future is in test or better not to split it at all for calibration). Can I do the same way for prob_calibration_function just by setting cv_folds='prefit'? I prefer not to split data at all and only fit because splitting may be done incorrectly for time series objects, it will mislead in a process of choosing parameters after considering results from cv if it performs automatically.

**Comment by blucena** [comment]
Your question 1 is essentially accurate.  `prob_calibration_function` does the heavy lifting given a set of predictions and the true answers and returns a function.  That function is then used as a "post-processing" step - mapping the uncalibrated model's predictions to their calibrated values.

The key is that the set of predictions that one passes to `prob_calibration_function` should not be on data that the model sees in training.  One way to achieve this is cross-validation, another is to have a completely separate holdout set that is used only for calibration.  The latter may make sense in your use case if you have a lot of data.

On question 2 - the `prob_calibration_function` has no cross-validation or anything in it itself (rather, it does its own cross-validation to select a regularization parameter, but that is a different issue than the cross-validation needed to address the previous issue).  The key is that the `y_pred` that is passed to `prob_calibration_function` are predictions made by models on unseen data (i.e. data that were not in the training set of the model).  This is because you want to find a calibration that works when models are predicting unseen data, and the pattern will obviously look quite different on the data points the model has already seen.

As you note, time series data complicates the process of cross-validation considerably, and the best path forward will be problem-specific.  If you have enough data, I would suggest using a completely separate `calibration` set.  In other words, you would just do the following steps:

1) Train your base model however you like (or keep a model that you already have)
2) Find (or holdout) data for which you know the answers (call them "y_true") but that the model did not see during training - call this the "calibration set"
3) Use your model to make predictions on the "calibration set" - call the results "y_pred"
4) Run `prob_calibration_function` on y_true, y_pred - call the resulting function `calib_func`
5) To make calibrated predictions on new data, use `calib_func(model.predict_proba(X_test)[:,1])`

Long answer :) hopefully it helps.

**Comment by AleksandrML** [comment]
yes, thank you very much,
I did it:). But anyway it is not solving the main question - saving function or model to use it on a product server, to use a calibrated model there. I tried to save a fit function also, it does not work unfortunately.

**Comment by blucena** [comment]
Agreed - I will work on finding a more elegant solution to save the SplineCalibratedClassifierCV object directly

**Comment by blucena** [comment]
This has now been addressed by version 0.1.0 and up.  The workflow has changed -- there is now a SplineCalib class equipped with a 'fit' and 'calibrate' method.  The object can then be saved and loaded using joblib.  See the example at:
[https://github.com/numeristical/introspective/blob/master/examples/SplineCalib_Tutorial.ipynb](https://github.com/numeristical/introspective/blob/master/examples/SplineCalib_Tutorial.ipynb)
